[project]
name = "jax-raytracer"
version = "0.1.0"
description = "A JAX-based WebGL ray-marcher"
readme = "README.md"
requires-python = "==3.12.6"
dependencies = [
    "numpy==2.1.1",
    "jax==0.4.34",
    "jaxlib==0.4.34",
    "tensorflowjs==4.22.0",
    "tensorflow>=2.17.1"
]
