[project]
name = "jax-raytracer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.10.12"
dependencies = [
    "numpy==1.26.4",
    "jax==0.4.25",
    "jaxlib==0.4.25",
    "tensorflowjs==4.17.0",
    "tensorflow==2.15.0"
]
